version: '3'

services:

  app:
    build:
      context: node
    container_name: app
    volumes:
      - ./node:/home/node/app
    entrypoint: wait-for db:3306 -t 40 -- ./start.sh
    networks:
      - node-network
    tty: true

  nginx:
    container_name: nginx
    build:
      context: nginx
    restart: always
    ports:
      - '8080:80'
    networks:
      - node-network

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
